### ISSUE TITLE
Thai UI Versions missing?

### ISSUE THREAD

**Issue by kagiura** [notofonts/thai#25]
### Issue
The Noto docs website still recommends using Thai UI in situations where vertical spacing is limited. Thai UI still proves useful for using alongside Noto Sans to not have differing line heights (see screenshot}; however, it seems to not have been ported over to this repository, and hasn't had an update ever since. Has the UI fonts been discontinued, or is it being maintained elsewhere? 

### Screenshot
<img width="587" alt="Screenshot 2023-05-09 at 11 50 52" src="https://user-images.githubusercontent.com/58155530/236996999-475e1014-56c7-4355-bc6d-dc8e853dbc6e.png">

**Comment by simoncozens** [comment]
The UI sources are in this repository, and builds are available at https://notofonts.github.io/thai/. We haven't done any new *releases* of those UI fonts, because I haven't made any changes to them. One reason I haven't made any changes to them is that UI fonts *are* deprecated; they were always a design compromise to deal with bad layout scenarios, and the solution there is not to compromise the design but to improve the layout system.

**Comment by kagiura** [comment]
Makes sense, thanks a lot! The Noto docs use guide still links to using UI fonts for Thai and Lao, so I was wondering if its just outdated or there was something I was missing.

**Comment by simoncozens** [comment]
Yeah, we need to update the docs too.
